# Generated by Django 5.2.8 on 2025-12-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodel_google_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_type',
            new_name='role',
        ),
    ]
