# Generated by Django 5.2.8 on 2026-02-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('JobApplication', 'Job Application'), ('StatusChange', 'Status Change'), ('NewMessage', 'New Message'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
