# Generated by Django 5.2.11 on 2026-02-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_user_role_alter_notification_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('StatusChange', 'Status Change'), ('JobMatchFound', 'Job Match Found'), ('JobApplication', 'Job Application'), ('AdminActions', 'Admin Actions'), ('JobExpired', 'Job Expired'), ('SubscriptionEnd', 'Subscription End'), ('RecruiterActions', 'Recruiter Actions'), ('NewSubscriber', 'New Subscriber'), ('UserRegistration', 'User Registration'), ('JobMatchSent', 'Job Match Sent'), ('JobPosted', 'Job Posted'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
