# Generated by Django 5.2.8 on 2025-12-09 10:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='draft_business_registration_doc',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='business_registration_document'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='draft_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='draft_company_logo'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='pending_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
