# Generated by Django 5.2.8 on 2025-12-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_recruiterprofile_draft_business_registration_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
