# Generated by Django 5.2.8 on 2025-12-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_recruiterprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='can_post_jobs',
            field=models.BooleanField(default=True),
        ),
    ]
