# Generated by Django 5.2.8 on 2026-01-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatattachmet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatAttachmet',
            new_name='ChatAttachment',
        ),
    ]
