# Generated by Django 5.2.8 on 2026-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_chatattachmet_chatattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
