# Generated by Django 5.2.8 on 2026-01-29 07:43

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("embeddings", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS job_embedding_idx
            ON embeddings_jobembedding
            USING ivfflat (embedding vector_cosine_ops)
            WITH (lists = 100);
            """,
            reverse_sql="DROP INDEX IF EXISTS job_embedding_idx;",
        )
    ]
