# Generated by Django 5.2.8 on 2026-01-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0002_add_vector_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobembedding',
            name='job',
        ),
    ]
