# Generated by Django 5.2.8 on 2026-01-29 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0003_remove_jobembedding_job'),
        ('jobs', '0006_alter_job_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobembedding',
            name='job',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='jobs.job'),
            preserve_default=False,
        ),
    ]
