# Generated by Django 5.2.8 on 2026-01-30 09:03

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0004_jobembedding_job'),
        ('profiles', '0004_delete_recruiterprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='profiles.jobseekerresume')),
            ],
            options={
                'indexes': [models.Index(fields=['resume'], name='embeddings__resume__3adbf0_idx')],
            },
        ),
    ]
