# Generated by Django 5.2.8 on 2026-01-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0005_resumeembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobembedding',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeembedding',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
