# Generated by Django 5.2.8 on 2026-02-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_job_application_deadline_job_education_requirement_and_more"),
        ("profiles", "0001_initial"),
        ("embeddings", "0006_jobembedding_source_text_resumeembedding_source_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobResumeInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strengths", models.JSONField()),
                ("gaps", models.JSONField()),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_insights",
                        to="jobs.job",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_insights",
                        to="profiles.jobseekerresume",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["job", "resume"], name="embeddings__job_id_4ece35_idx")],
                "unique_together": {("job", "resume")},
            },
        ),
    ]
