# Generated by Django 5.2.12 on 2026-03-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0007_jobresumeinsight'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobresumeinsight',
            new_name='embeddings__job_id_1f330c_idx',
            old_name='embeddings__job_id_4ece35_idx',
        ),
    ]
