# Generated by Django 5.2.8 on 2025-12-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='current_salary',
            field=models.PositiveIntegerField(blank=True, help_text='Current salary in INR', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.PositiveIntegerField(default=123, help_text='Expected salary in INR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notice_period',
            field=models.CharField(blank=True, help_text='Notice period (e.g. 30 days, Immediate)', max_length=50),
        ),
    ]
