# Generated by Django 5.2.8 on 2026-01-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplication_current_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='recruiter_notes',
            field=models.TextField(blank=True),
        ),
    ]
