# Generated by Django 5.2.8 on 2026-01-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_jobapplication_recruiter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='current_role',
            field=models.CharField(default='software engineer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(default='kochi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default=9876543213, max_length=20),
            preserve_default=False,
        ),
    ]
