# Generated by Django 5.2.8 on 2026-01-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobapplication_current_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='current_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
