# Generated by Django 5.2.8 on 2026-01-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_jobapplication_current_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='match_score',
            field=models.FloatField(blank=True, help_text='AI similarity score between resume and job (0-100)', null=True),
        ),
    ]
