# Generated by Django 5.2.8 on 2026-01-31 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_jobapplication_match_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.JSONField()),
                ('gaps', models.JSONField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='applications.jobapplication')),
            ],
        ),
    ]
