# Generated by Django 5.2.8 on 2026-01-31 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_applicationinsight'),
        ('profiles', '0004_delete_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applied_resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='profiles.jobseekerresume'),
        ),
    ]
