# Generated by Django 5.2.8 on 2025-12-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            # FORWARD
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            # REVERSE
            "DROP EXTENSION IF EXISTS pg_trgm;"
        )
    ]