# Generated by Django 5.2.8 on 2025-12-17 07:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
