# Generated by Django 5.2.8 on 2025-12-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]


    operations = [
        migrations.RunSQL(
            # ======================= FORWARD =======================
            """
            /*
            ---------------------------------------------------------
            1. Helper function for BEFORE trigger
               - Uses ONLY row data
               - NO cross-table access
               - SAFE in BEFORE INSERT/UPDATE
            ---------------------------------------------------------
            */
            CREATE OR REPLACE FUNCTION build_job_vector_from_fields(
                job_title TEXT,
                job_description TEXT
            )
            RETURNS tsvector AS $$
            BEGIN
                RETURN to_tsvector(
                    'english',
                    COALESCE(job_title, '') || ' ' ||
                    COALESCE(job_description, '')
                );
            END;
            $$ LANGUAGE plpgsql;


            /*
            ---------------------------------------------------------
            2. BEFORE trigger on jobs_job
               - No UPDATE on same table
               - No recursion
            ---------------------------------------------------------
            */
            CREATE OR REPLACE FUNCTION job_before_save_search_vector()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.search_vector :=
                    build_job_vector_from_fields(
                        NEW.title,
                        NEW.description
                    );
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;


            /*
            ---------------------------------------------------------
            3. AFTER trigger on jobs_job_skills (M2M)
               - SAFE to update jobs_job
               - Handles skills add/remove
            ---------------------------------------------------------
            */
            CREATE OR REPLACE FUNCTION job_skill_after_change()
            RETURNS TRIGGER AS $$
            DECLARE
                target_job_id BIGINT;
            BEGIN
                target_job_id := COALESCE(NEW.job_id, OLD.job_id);

                UPDATE jobs_job
                SET search_vector =
                    to_tsvector(
                        'english',
                        COALESCE(title, '') || ' ' ||
                        COALESCE(description, '') || ' ' ||
                        COALESCE(
                            (
                                SELECT string_agg(s.name, ' ')
                                FROM jobs_job_skills jjs
                                JOIN jobs_jobskill s
                                  ON s.id = jjs.jobskill_id
                                WHERE jjs.job_id = target_job_id
                            ),
                            ''
                        )
                    )
                WHERE id = target_job_id;

                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;


            /*
            ---------------------------------------------------------
            4. Triggers
            ---------------------------------------------------------
            */
            CREATE TRIGGER job_search_vector_before_save
            BEFORE INSERT OR UPDATE
            ON jobs_job
            FOR EACH ROW
            EXECUTE FUNCTION job_before_save_search_vector();

            CREATE TRIGGER job_search_vector_after_skill_change
            AFTER INSERT OR DELETE
            ON jobs_job_skills
            FOR EACH ROW
            EXECUTE FUNCTION job_skill_after_change();
            """,

            # ======================= REVERSE =======================
            """
            DROP TRIGGER IF EXISTS job_search_vector_after_skill_change ON jobs_job_skills;
            DROP TRIGGER IF EXISTS job_search_vector_before_save ON jobs_job;

            DROP FUNCTION IF EXISTS job_skill_after_change();
            DROP FUNCTION IF EXISTS job_before_save_search_vector();
            DROP FUNCTION IF EXISTS build_job_vector_from_fields(TEXT, TEXT);
            """
        )
    ]