# Generated by Django 5.2.8 on 2025-12-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_search_triggers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
