# Generated by Django 5.2.8 on 2025-12-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_search_vector_job_jobs_job_search__684d46_gin'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER job_search_vector_update
            BEFORE INSERT OR UPDATE ON jobs_job
            FOR EACH ROW EXECUTE FUNCTION
            tsvector_update_trigger(
                search_vector,
                'pg_catalog.english',
                title,
                description,
                skills
            );
            """,
            reverse_sql="DROP TRIGGER IF EXISTS job_search_vector_update ON jobs_job;"
        )
    ]
