# Generated by Django 5.2.8 on 2026-01-19 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_delete_jobapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='jobs_savedj_user_id_e6c86a_idx'), models.Index(fields=['job'], name='jobs_savedj_job_id_4fa456_idx'), models.Index(fields=['user', 'job'], name='jobs_savedj_user_id_ad1615_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'user'), name='unique_active_saved_job_per_user')],
            },
        ),
    ]
