# Generated by Django 5.2.8 on 2025-12-20 06:19

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_add_search_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GistIndex(fields=['title'], name='job_title_trgm_idx', opclasses=['gist_trgm_ops']),
        ),
    ]
