# Generated by Django 5.2.8 on 2026-01-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_savedjob'),
        ('recruiter', '0004_recruiterprofile_can_post_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiter.recruiterprofile'),
        ),
    ]
