# Generated by Django 5.2.11 on 2026-02-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_user_id_1a6c3e_idx',
            old_name='support_supp_user_id_f01a0b_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_status_eeda74_idx',
            old_name='support_supp_status_44f90e_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticketmessage',
            new_name='support_sup_ticket__86cbdc_idx',
            old_name='support_supp_ticket__e03266_idx',
        ),
    ]
