# Generated by Django 5.2.9 on 2025-12-05 04:35

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_jobseekerprofile_notice_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerresume',
            name='url',
        ),
        migrations.AddField(
            model_name='jobseekerresume',
            name='file',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
