# Generated by Django 5.2.8 on 2025-12-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_jobseekerresume_url_jobseekerresume_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecruiterProfile',
        ),
    ]
