# Generated by Django 5.2.11 on 2026-02-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_delete_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerresume',
            name='parsing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerresume',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSING', 'Parsing'), ('PARSED', 'Parsed'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
    ]
